export interface RestaurantData {
  opnsfteamcode: string; // 개방자치단체코드
  mgtno: string; // 관리번호
  apvpermymd: string; // 인허가일자
  apvcancelymd: string; // 인허가취소일자
  trdstategbn: string; // 영업상태구분코드
  trdstatenm: string; // 영업상태명
  dtlstategbn: string; // 상세영업상태코드
  dtlstatenm: string; // 상세영업상태명
  dcbymd: string; // 폐업일자
  clgstdt: string; // 휴업시작일자
  clgenddt: string; // 휴업종료일자
  ropnymd: string; // 재개업일자
  sitetel: string; // 소재지전화
  sitearea: string; // 소재지면적
  sitepostno: string; // 소재지우편번호
  sitewhladdr: string; // 소재지전체주소
  rdnwhladdr: string; // 소재지도로명전체주소
  rdnpostno: string; // 소재지도로명우편번호
  bplcnm: string; // 사업장명
  lastmodts: string; // 최종수정시점
  updategbn: string; // 데이터갱신구분
  updatedt: string; // 데이터갱신일자
  uptaenm: string; // 업태명
  x: string; // 좌표정보(x)
  y: string; // 좌표정보(y)
  sntuptaenm: string; // 위생업태명
  maneipcnt: string; // 남성종사자수
  wmeipcnt: string; // 여성종사자수
  trdpjubnsenm: string; // 영업장주변구분명
  lvsenm: string; // 등급구분명
  wtrsplyfacilsenm: string; // 급수시설구분명
  totepnum: string; // 총종업원수
  hoffepcnt: string; // 본사종업원수
  fctyowkepcnt: string; // 공장사무직종업원수
  fctysiljobepcnt: string; // 공장판매직종업원수
  fctypdtjobepcnt: string; // 공장생산직종업원수
  bdngownsenm: string; // 건물소유구분명
  isream: string; // 보증액
  monam: string; // 월세액
  multusnupsoyn: string; // 다중이용업소여부
  faciltotscp: string; // 시설총규모
  jtupsoasgnno: string; // 전통업소지정번호
  jtupsomainedf: string; // 전통업소주된음식
  homepage: string; // 홈페이지
}
